### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by TiboOpGithub** [DeflatedPickle/Restock#1]
Can u make a 1.17 version of this?

**Comment by TiboOpGithub** [comment]
Do you mean that the mod also works on 1.17.1 or do you mean something else?

**Comment by DeflatedPickle** [comment]
I don't do backports. If you want it, do it yourself. The source is right here

**Comment by TiboOpGithub** [comment]
Oh, that's too bad! I have no idea how to do it myself
